Repository kookmin-sw/capstone-2020-2, pull requests merged in 2020-05, with the labels that each got.

#41 Back - video session, solve error, video api
  src/back-end/FBI/api/models.py
  src/back-end/FBI/api/views.py
  src/front-end/src/components/Login.js
Labels: backend, bug, enhancement, frontend

#42 Front
  src/front-end/package-lock.json
  src/front-end/package.json
  src/front-end/src/App.css
  src/front-end/src/App.js
  src/front-end/src/components/Main.js
  src/front-end/src/components/Signup.js
  src/front-end/src/components/VideoPlay.js
Labels: enhancement, frontend

#50 Front
  src/back-end/FBI/.vscode/settings.json
  src/back-end/FBI/FBI/settings.py
  src/back-end/FBI/api/customLogin.py
  src/front-end/.eslintrc
  src/front-end/.eslintrc.json
  src/front-end/.prettierrc
  src/front-end/.vscode/settings.json
  src/front-end/package-lock.json
  src/front-end/package.json
  src/front-end/src/App.css
  src/front-end/src/App.js
  src/front-end/src/UserContext.js
  src/front-end/src/components/Analyze.js
  src/front-end/src/components/IntroCarousel.js
  src/front-end/src/components/Login.js
  src/front-end/src/components/Main.js
  src/front-end/src/components/Option.js
  src/front-end/src/components/Signup.js
  src/front-end/src/components/VideoPlay.js
  src/front-end/src/components/loginSuccessAlert.js
  src/front-end/src/index.js
  src/front-end/src/pages/Analyze.js
  src/front-end/src/pages/Login.js
  src/front-end/src/pages/Main.js
  src/front-end/src/pages/Option.js
  src/front-end/src/pages/Signup.js
  src/front-end/src/pages/TrialOption.js
  src/front-end/src/pages/VideoPlay.js
  src/front-end/src/serviceWorker.js
  src/front-end/yarn.lock
Labels: frontend

#48 Back to milestone-2
  src/back-end/FBI/api/urls.py
  src/back-end/FBI/api/views.py
Labels: backend

#52 Face to milestone-2
  src/face/FaceEmotionModel.pt
  src/face/face_emotion.py
  src/face/multimodal_decision.py
  src/face/predict_face_emotion.py
  src/face/predict_face_emotion_faceapi.py
Labels: face(emotion)

#55 Merge eeg to milestone-2
  src/eeg/.ipynb_checkpoints/Train EEG based Emotion Classifier (1)-checkpoint.ipynb
  src/eeg/.ipynb_checkpoints/Train EEG based Emotion Classifier-checkpoint.ipynb
  src/eeg/.ipynb_checkpoints/Transform dataset into an input Formation-checkpoint.ipynb
  src/eeg/BrainFlow.ipynb
  src/eeg/CustomDatasetClass.py
  src/eeg/Models.py
  src/eeg/Test_EEG_Classifier.pth
  src/eeg/Train EEG based Emotion Classifier.ipynb
  src/eeg/TrainTestModule.py
  src/eeg/Transform dataset into an input Formation.ipynb
  src/eeg/eegAnalyzeModule.py
  src/eeg/preprocessModule.py
  src/eeg/record_signal.py
  src/eeg/sensorModule.py
Labels: branch

#57 Feat : Modify Predict Face Emotion and Add Haar
  src/face/haarcascade_frontalface_default.xml
  src/face/predict_face_emotion_faceapi.py
Labels: face(emotion)
