Repository kookmin-sw/capstone-2020-2, pull requests merged in 2020-04, with the labels that each got.

#13 Back
  src/back-end/.gitignore
  src/back-end/FBI/.idea/.gitignore
  src/back-end/FBI/.idea/FBI.iml
  src/back-end/FBI/.idea/encodings.xml
  src/back-end/FBI/.idea/inspectionProfiles/profiles_settings.xml
  src/back-end/FBI/.idea/misc.xml
  src/back-end/FBI/.idea/modules.xml
  src/back-end/FBI/.idea/vcs.xml
  src/back-end/FBI/FBI/__init__.py
  src/back-end/FBI/FBI/__pycache__/__init__.cpython-37.pyc
  src/back-end/FBI/FBI/__pycache__/settings.cpython-37.pyc
  src/back-end/FBI/FBI/__pycache__/urls.cpython-37.pyc
  src/back-end/FBI/FBI/__pycache__/wsgi.cpython-37.pyc
  src/back-end/FBI/FBI/asgi.py
  src/back-end/FBI/FBI/settings.py
  src/back-end/FBI/FBI/urls.py
  src/back-end/FBI/FBI/wsgi.py
  src/back-end/FBI/api/__init__.py
  src/back-end/FBI/api/__pycache__/__init__.cpython-37.pyc
  src/back-end/FBI/api/__pycache__/admin.cpython-37.pyc
  src/back-end/FBI/api/__pycache__/models.cpython-37.pyc
  src/back-end/FBI/api/__pycache__/serializers.cpython-37.pyc
  src/back-end/FBI/api/__pycache__/urls.cpython-37.pyc
  src/back-end/FBI/api/__pycache__/views.cpython-37.pyc
  src/back-end/FBI/api/admin.py
  src/back-end/FBI/api/apps.py
  src/back-end/FBI/api/models.py
  src/back-end/FBI/api/serializers.py
  src/back-end/FBI/api/tests.py
  src/back-end/FBI/api/urls.py
  src/back-end/FBI/api/views.py
  src/back-end/FBI/manage.py
Labels: enhancement

#27 Back - Logout and video in trial
  src/back-end/FBI/FBI/__pycache__/settings.cpython-37.pyc
  src/back-end/FBI/api/__pycache__/urls.cpython-37.pyc
  src/back-end/FBI/api/__pycache__/views.cpython-37.pyc
  src/back-end/FBI/api/urls.py
  src/back-end/FBI/api/views.py
Labels: backend

#28 Eeg
  src/eeg/.ipynb_checkpoints/BrainFlow-checkpoint.ipynb
  src/eeg/BrainFlow.ipynb
  src/eeg/Train EEG based Emotion Classifier (1).ipynb
  src/eeg/Train EEG based Emotion Classifier.ipynb
  src/eeg/Transform dataset into an input Formation.ipynb
  src/eeg/Visualize processed signals.ipynb
  src/eeg/meta_data.py
  src/eeg/plotModule.py
  src/eeg/preprocessModule.py
  src/eeg/transformModule.py
Labels: eeg, enhancement
